src/Parser/EnvParser.cs

Fixed the issue when the parser did not return the correct line number in a Windows environment

---

example/Program.cs
src/Configuration/EnvParserOptions.cs
src/Constants/ExceptionMessages.cs
src/Interfaces/IEnvLoader.cs
src/Interfaces/IEnvParser.cs
src/Loader/EnvLoader.ConfigurationMethods.cs
src/Loader/EnvLoader.cs
src/Parser/EnvParser.ConfigurationMethods.cs
src/Parser/EnvParser.HelperMethods.cs
src/Parser/EnvParser.cs
tests/Parser/EnvParserOptionsTests.cs
tests/Parser/EnvParserTests.cs

Added an option to avoid the parser from modifying the environment

---

src/Constants/EnvironmentNames.cs
src/Helpers/Env.cs
tests/Helpers/EnvTests.cs

Added a helper class to perform checks with the current environment

---

src/Helpers/EnvReader.cs
src/Interfaces/IEnvReader.cs
tests/Helpers/EnvReaderTests.cs

Added a 'Exists()' method to the EnvReader class

---

src/Loader/EnvLoader.cs
tests/Loader/EnvLoaderTests.cs
tests/Loader/env_files/local/.env
tests/Loader/env_files/local/.env.dev
tests/Loader/env_files/local/.env.dev.local
tests/Loader/env_files/local/.env.example1
tests/Loader/env_files/local/.env.example2
tests/Loader/env_files/local/.env.local

 Fixed problem with 'LoadEnv' method not maintaining .env files priority

---

src/Helpers/Env.cs
src/Helpers/EnvReader.WithTry.cs
src/Helpers/EnvReader.cs
src/Interfaces/IEnvLoader.cs
src/Interfaces/IEnvParser.cs
src/Interfaces/IEnvReader.cs
src/Loader/EnvLoader.ConfigurationMethods.cs
src/Loader/EnvLoader.cs
src/Parser/EnvParser.HelperMethods.cs
src/Parser/EnvParser.cs
tests/Parser/EnvValidationResultTests.cs

Added checks to some methods in case the parameter is null

---

src/Interfaces/IEnvLoader.cs
src/Loader/EnvLoader.ConfigurationMethods.cs

Added a configuration method to set the encoding through its name

---

src/Configuration/EnvValidatorOptions.cs
src/Constants/ExceptionMessages.cs
src/Exceptions/EnvVariableNotFoundException.cs
src/Extensions/EnumerableExtensions.cs
src/Helpers/EnvValidator.cs
src/Interfaces/IEnvValidator.cs
tests/Helpers/EnvValidatorTests.cs

Added a class that validates whether the keys required by the application exist in the current environment

---

src/Interfaces/IEnvLoader.cs
src/Loader/EnvLoader.ConfigurationMethods.cs
src/Loader/EnvLoader.HelperMethods.cs
src/Loader/EnvLoader.cs
tests/Loader/EnvLoaderTests.cs

Added a configuration method to indicate that a .env file is optional

---

src/Configuration/EnvLoaderOptions.cs
src/Interfaces/IEnvLoader.cs
src/Loader/EnvLoader.ConfigurationMethods.cs
src/Loader/EnvLoader.HelperMethods.cs
src/Loader/EnvLoader.cs
tests/Loader/EnvLoaderTests.cs

Added a configuration method to indicate that all .env files should be optional 

---

src/Helpers/EnvReader.WithTry.cs
src/Helpers/EnvReader.cs

Added a dependency to the 'EnvReader' class 

---

src/Helpers/EnvReader.cs
src/Interfaces/IEnvReader.cs
tests/Helpers/EnvReaderTests.cs

Resolves #26 
Changes:
- The name of the `Exists` method has been changed.

Added a 'HasValue()' method to the 'EnvReader' class

---

src/Interfaces/IEnvLoader.cs
src/Interfaces/IEnvParser.cs
src/Loader/EnvLoader.ConfigurationMethods.cs
src/Parser/EnvParser.ConfigurationMethods.cs
tests/CustomEnvironmentVariablesProvider.cs
tests/Helpers/EnvValidatorTests.cs
tests/Parser/EnvParserOptionsTests.cs

Added a configuration method to set the environment variables provider

---

tests/Parser/EnvParserTests.cs

A unit test has been updated for issue #62

---

src/Constants/ExceptionMessages.cs
src/Helpers/FormattingMessage.cs
src/Loader/EnvLoader.cs
tests/Loader/EnvLoaderTests.LoadEnv.cs

Fixed the problem that DOTNET_ENV is not set when the environment name is defined from the source code

---

example/DotEnv.Core.Example.csproj
example/Program.cs
src/DotEnv.Core.csproj
tests/DotEnv.Core.Tests.csproj

**Other changes:**
- Added support with .NET 6 for the test and example project.
Resolves #79

 Added support for C# 10

---

src/Binder/EnvBinder.cs
src/Extensions/StringExtensions.cs
tests/Binder/AppSettings.cs
tests/Binder/EnvBinderTests.cs

Added conversion of properties to `UpperCaseSnakeCase`

---

src/Loader/EnvLoader.cs
src/Parser/EnvParser.HelperMethods.cs
tests/Loader/EnvLoaderTests.LoadEnv.cs
tests/Loader/EnvLoaderTests.cs

For more information: https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#commenting-conventions

Added C# Commenting conventions

---

docs/articles/accessing_environment_variables.md
docs/articles/dependency_injection.md
docs/articles/getting_started.md
docs/articles/load_envfile_based_environment.md
docs/articles/required_keys.md
docs/articles/using_binder.md
docs/articles/using_dotenv_aspnetcore.md
docs/articles/using_parser.md

See https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#commenting-conventions

Changes the commenting conventions of the documentation

---

src/Parser/EnvParser.ConfigurationMethods.cs
src/Parser/EnvParser.HelperMethods.cs
src/Parser/EnvParser.cs
src/Parser/EnvParserOptions.cs
tests/Parser/EnvParserTests.Options.cs
tests/Parser/EnvParserTests.cs

 Ignore inline comments when using the tab key

---

Directory.Packages.props
DotEnv.Core.sln
samples/DotEnv.Example.AspNetCore/DotEnv.Example.AspNetCore.csproj
samples/DotEnv.Example.AspNetFramework/DotEnv.Example.AspNetFramework.csproj
samples/DotEnv.Example.ConfigurationApi/DotEnv.Example.ConfigurationApi.csproj
samples/DotEnv.Example.NetFramework/DotEnv.Example.NetFramework.csproj
samples/DotEnv.Example.OptionsPattern/DotEnv.Example.OptionsPattern.csproj
samples/DotEnv.Example/DotEnv.Core.Example.csproj
tests/DotEnv.Core.Tests.csproj

See https://devblogs.microsoft.com/nuget/introducing-central-package-management/

Added support for central package management

---

Directory.Build.props
plugins/Microsoft.Extensions.DI/example/DotEnv.Extensions.Microsoft.DI.Example.csproj
plugins/Microsoft.Extensions.DI/tests/DotEnv.Extensions.Microsoft.DI.Tests.csproj
samples/DotEnv.Example.AspNetCore/DotEnv.Example.AspNetCore.csproj
samples/DotEnv.Example.Binding/DotEnv.Example.Binding.csproj
samples/DotEnv.Example.ConfigurationApi/DotEnv.Example.ConfigurationApi.csproj
samples/DotEnv.Example.OptionsPattern/DotEnv.Example.OptionsPattern.csproj
samples/DotEnv.Example.Parsing/DotEnv.Example.Parsing.csproj
samples/DotEnv.Example.RequiredKeys/DotEnv.Example.RequiredKeys.csproj
samples/DotEnv.Example.SharedSettings/ConsoleAppOne/ConsoleAppOne.csproj
samples/DotEnv.Example.SharedSettings/ConsoleAppTwo/ConsoleAppTwo.csproj
samples/DotEnv.Example/DotEnv.Core.Example.csproj
tests/DotEnv.Core.Tests.csproj

This file defines the target framework for all projects.

chore: Add Directory.Build.props file

---

src/Constants/EnvironmentNames.cs

See https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlylist-1

refactor: Use IReadOnlyList interface in EnvironmentNames

---

plugins/Microsoft.Extensions.DI/tests/ServiceCollectionExtensionsTests.cs

This PR serves as documentation on the correct use of “using”.

test: Use the "using" statement to free resources

---

src/Binder/EnvBinder.cs
src/Common/EnvValidationResult.cs
src/Loader/EnvLoader.cs
src/Loader/EnvLoaderOptions.cs
src/Parser/EnvParser.cs
src/Validator/EnvValidator.cs

See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0300

refactor: Use collection expression to create empty collections

---

plugins/Microsoft.Extensions.DI/tests/ServiceCollectionExtensionsTests.cs

See https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#naming-your-tests
> **The name of your test should consist of three parts:**
> * The name of the method being tested.
> * The scenario under which it's being tested.
> * The expected behavior when the scenario is invoked.

test: Apply a naming convention to test names
